---

Reconecte ao Drive.

In [1]:
import os
DRIVE_DIRECTORY = "curso_ml"
DRIVE_DIRECTORY = os.path.join("/content/drive/MyDrive", DRIVE_DIRECTORY)



---

In [2]:
!pip install pyECLAT

Requirement already satisfied: pyECLAT in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.0.2)
Requirement already satisfied: pandas>=0.25.3 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pyECLAT) (2.2.2)
Requirement already satisfied: numpy>=1.17.4 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pyECLAT) (1.26.4)
Requirement already satisfied: tqdm>=4.41.1 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pyECLAT) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=0.25.3->pyECLAT) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=0.25.3->pyECLAT) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=0.25.3->pyECLAT) (2024.1)
Requirement already satisfied: six>=1.5 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.16.0)
Requirement already satisfied: colorama in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tqdm>=4.41.1->pyECLAT) (0.4.6)

In [3]:
import pandas as pd

from pyECLAT import ECLAT

## Algoritmo ECLAT

Carregue a lista de compras a partir do arquivo `itemlist.txt` na pasta do Drive, como um DataFrame do Pandas, lembre-se de selecionar o delimitador adequado.

In [4]:
base = pd.read_csv(os.path.join(DRIVE_DIRECTORY, 'itemlist.txt'), delimiter=';', header=None)
base

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,...,JAM MAKING SET WITH JARS,JAM MAKING SET PRINTED,SET OF 4 PANTRY JELLY MOULDS,RABBIT NIGHT LIGHT,LUNCH BAG APPLE DESIGN,SPOTTY BUNTING,PARTY BUNTING,WOODEN PICTURE FRAME WHITE FINISH,JUMBO BAG RED RETROSPOT,WHITE HANGING HEART T-LIGHT HOLDER
1,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SUKI DESIGN,LUNCH BAG PINK POLKADOT,JUMBO SHOPPER VINTAGE RED PAISLEY,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,HEART OF WICKER SMALL,...,WHITE HANGING HEART T-LIGHT HOLDER,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,NaN,NaN,NaN,NaN,NaN
2,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG SUKI DESIGN,LUNCH BAG PINK POLKADOT,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,RECIPE BOX PANTRY YELLOW DESIGN,...,WHITE HANGING HEART T-LIGHT HOLDER,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,NaN,NaN,NaN,NaN,NaN
3,ALARM CLOCK BAKELIKE RED,JAM MAKING SET WITH JARS,JAM MAKING SET PRINTED,SET OF 4 PANTRY JELLY MOULDS,RABBIT NIGHT LIGHT,LUNCH BAG APPLE DESIGN,JUMBO BAG RED RETROSPOT,WHITE HANGING HEART T-LIGHT HOLDER,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,...,GREEN REGENCY TEACUP AND SAUCER,ROSES REGENCY TEACUP AND SAUCER,SET OF 3 CAKE TINS PANTRY DESIGN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG SUKI DESIGN,...,SPOTTY BUNTING,PARTY BUNTING,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12783,PARTY BUNTING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12784,JUMBO BAG RED RETROSPOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12785,POSTAGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12786,POSTAGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12787,JUMBO BAG PINK POLKADOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Instancie uma classe de ECLAT, informando o DataFrame.

In [5]:
eclat = ECLAT(data=base)

Exiba o DataFrame no formato binário.

In [6]:
eclat.df_bin

,LUNCH BAG WOODLAND,ALARM CLOCK BAKELIKE RED,LUNCH BAG APPLE DESIGN,JAM MAKING SET PRINTED,LUNCH BAG SUKI DESIGN,WHITE HANGING HEART T-LIGHT HOLDER,RABBIT NIGHT LIGHT,GREEN REGENCY TEACUP AND SAUCER,PARTY BUNTING,JUMBO SHOPPER VINTAGE RED PAISLEY,...,LUNCH BAG PINK POLKADOT,JUMBO STORAGE BAG SUKI,WOODEN PICTURE FRAME WHITE FINISH,LUNCH BAG BLACK SKULL.,ASSORTED COLOUR BIRD ORNAMENT,RECIPE BOX PANTRY YELLOW DESIGN,HEART OF WICKER SMALL,PACK OF 72 RETROSPOT CAKE CASES,SET OF 4 PANTRY JELLY MOULDS,SET OF 3 CAKE TINS PANTRY DESIGN
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,1,1,1,1,1
1,1,1,1,1,1,1,1,1,0,1,...,1,1,0,1,0,1,1,1,1,1
2,1,1,1,1,1,1,1,1,0,0,...,1,1,1,1,1,1,0,1,0,1
3,0,1,1,1,1,1,1,1,0,0,...,1,1,0,1,0,1,1,1,1,1
4,1,1,0,1,1,1,1,1,1,0,...,0,1,0,1,0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12783,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12784,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12785,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12786,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12787,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Exiba os valores das colunas, que representam os itens deste problema.

In [ ]:
___

Ajuste o algoritmo ECLAT, utilizando o mesmo suporte mínimo do exercício do algoritmo apriori ($0.02$), e solicitando `min_combination=1` e `max_combination=3`.

In [ ]:
indices, support = ___

Exiba os itens e suas respectivas transações.

In [ ]:
___

Quantos itemsets foram gerados?

In [ ]:
___

Exiba os itens e seus respectivos suportes.

In [ ]:
___